
macro(add_opifex_fmod APPLICATION_TARGET )

	if(${OPIFEX_OPTION_FMOD})
		include_directories(../External/FMod/include/)

		if(${OPIFEX_OS_WIN64})
			target_link_libraries(${APPLICATION_TARGET}  ${PROJECT_SOURCE_DIR}/External/FMod/lib/win64/fmod64_vc.lib)
			target_link_libraries(${APPLICATION_TARGET}  ${PROJECT_SOURCE_DIR}/External/FMod/lib/win64/fmodL64_vc.lib)
			copy_file_to_binaries(/External/FMod/lib/win64/fmod64.dll)
			copy_file_to_binaries(/External/FMod/lib/win64/fmodL64.dll)
		elseif(${OPIFEX_OS_WIN32})
			target_link_libraries(${APPLICATION_TARGET}  ${PROJECT_SOURCE_DIR}/External/FMod/lib/win32/fmod_vc.lib)
			target_link_libraries(${APPLICATION_TARGET}  ${PROJECT_SOURCE_DIR}/External/FMod/lib/win32/fmodL_vc.lib)
			copy_file_to_binaries(/External/FMod/lib/win32/fmod.dll)
			copy_file_to_binaries(/External/FMod/lib/win32/fmodL.dll)
		elseif(${OPIFEX_OS_OSX64})
			target_link_libraries(${APPLICATION_TARGET}  ${PROJECT_SOURCE_DIR}/External/FMod/lib/libfmod.dylib)
			target_link_libraries(${APPLICATION_TARGET}  ${PROJECT_SOURCE_DIR}/External/FMod/lib/libfmodL.dylib)
			copy_file_to_binaries(/External/FMod/lib/libfmod.dylib)
			copy_file_to_binaries(/External/FMod/lib/libfmodL.dylib)
		endif()

		if(${OPIFEX_OPTION_RELEASE})
			if(${OPIFEX_OS_WIN64})
				copy_to_folder(${APPLICATION_TARGET} "/External/FMod/lib/" "fmod64.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
				copy_to_folder(${APPLICATION_TARGET} "/External/FMod/lib/" "fmodL64.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
			else()
				copy_to_folder(${APPLICATION_TARGET} "/External/FMod/lib/" "fmod.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
				copy_to_folder(${APPLICATION_TARGET} "/External/FMod/lib/" "fmodL.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
			endif()
		else()
			if(${OPIFEX_OS_WIN64})
				copy_to_folder_msvc(${APPLICATION_TARGET} "/External/FMod/lib/" "fmod64.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
				copy_to_folder_msvc(${APPLICATION_TARGET} "/External/FMod/lib/" "fmodL64.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
			else()
				copy_to_folder_msvc(${APPLICATION_TARGET} "/External/FMod/lib/" "fmod.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
				copy_to_folder_msvc(${APPLICATION_TARGET} "/External/FMod/lib/" "fmodL.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
			endif()
		endif()
	endif()

endmacro(add_opifex_fmod)
