
macro(add_opifex_physx APPLICATION_TARGET )

	if(${OPIFEX_OPTION_PHYSX})

		message(STATUS "Link Physics")
		include_directories(../External/PhysX/include/)

        if(${OPIFEX_OS_WINDOWS})
			if(${OPIFEX_OS_WIN64})
				if(${OPIFEX_OPTION_RELEASE})
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3_x64.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysXProfileSDK.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/LowLevel.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/LowLevelCloth.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3CharacterKinematic_x64.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3Common_x64.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3Cooking_x64.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3Extensions.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3Vehicle.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysXVisualDebuggerSDK.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PxTask.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PvdRuntime.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/SceneQuery.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/SimulationController.lib)

					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3_x64.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysXProfileSDK.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/LowLevel.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/LowLevelCloth.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3CharacterKinematic_x64.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3Common_x64.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3Cooking_x64.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3Extensions.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3Vehicle.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysXVisualDebuggerSDK.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PxTask.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PvdRuntime.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/SceneQuery.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/SimulationController.lib)

					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3CharacterKinematic_x64.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3Common_x64.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3Cooking_x64.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3_x64.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3Gpu_x64.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysXDevice64.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "nvToolsExt64_1.dll" "/Application/Release" ${OPIFEX_OS_WINDOWS})
				else()

					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3DEBUG_x64.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysXProfileSDKDEBUG.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/LowLevelDEBUG.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/LowLevelClothDEBUG.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3CharacterKinematicDEBUG_x64.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3CommonDEBUG_x64.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3CookingDEBUG_x64.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3ExtensionsDEBUG.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysX3VehicleDEBUG.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PhysXVisualDebuggerSDKDEBUG.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PxTaskDEBUG.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/PvdRuntimeDEBUG.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/SceneQueryDEBUG.lib)
					target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win64/SimulationControllerDEBUG.lib)

					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3DEBUG_x64.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysXProfileSDKDEBUG.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/LowLevelDEBUG.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/LowLevelClothDEBUG.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3CharacterKinematicDEBUG_x64.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3CommonDEBUG_x64.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3CookingDEBUG_x64.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3ExtensionsDEBUG.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysX3VehicleDEBUG.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PhysXVisualDebuggerSDKDEBUG.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PxTaskDEBUG.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/PvdRuntimeDEBUG.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/SceneQueryDEBUG.lib)
					copy_file_to_binaries(/External/PhysX/lib/win64/SimulationControllerDEBUG.lib)

					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3CharacterKinematicDEBUG_x64.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3CommonDEBUG_x64.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3CookingDEBUG_x64.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3DEBUG_x64.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3GpuDEBUG_x64.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysXDevice64.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
					copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "nvToolsExt64_1.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
				endif()
			else()
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/PhysX3DEBUG_x86.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/PhysXProfileSDKDEBUG.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/LowLevelDEBUG.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/LowLevelClothDEBUG.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/PhysX3CharacterKinematicDEBUG_x86.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/PhysX3CommonDEBUG_x86.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/PhysX3CookingDEBUG_x86.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/PhysX3ExtensionsDEBUG.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/PhysX3VehicleDEBUG.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/PhysXVisualDebuggerSDKDEBUG.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/PxTaskDEBUG.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/PvdRuntimeDEBUG.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/SceneQueryDEBUG.lib)
				target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/win32/SimulationControllerDEBUG.lib)

				copy_file_to_binaries(/External/PhysX/lib/win32/PhysX3DEBUG_x86.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/PhysXProfileSDKDEBUG.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/LowLevelDEBUG.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/LowLevelClothDEBUG.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/PhysX3CharacterKinematicDEBUG_x86.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/PhysX3CommonDEBUG_x86.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/PhysX3CookingDEBUG_x86.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/PhysX3ExtensionsDEBUG.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/PhysX3VehicleDEBUG.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/PhysXVisualDebuggerSDKDEBUG.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/PxTaskDEBUG.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/PvdRuntimeDEBUG.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/SceneQueryDEBUG.lib)
				copy_file_to_binaries(/External/PhysX/lib/win32/SimulationControllerDEBUG.lib)

				copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3CharacterKinematicDEBUG_x86.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
				copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3CommonDEBUG_x86.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
				copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3CookingDEBUG_x86.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
				copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3DEBUG_x86.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
				copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysX3GpuDEBUG_x86.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
				copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "PhysXDevice32.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
				copy_to_folder(${APPLICATION_TARGET} "/External/PhysX/lib/" "nvToolsExt32_1.dll" "/Application/Debug" ${OPIFEX_OS_WINDOWS})
            endif()
        elseif(${OPIFEX_OS_OSX64})
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libPhysX3DEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libPhysXProfileSDKDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libLowLevelDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libLowLevelClothDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libPhysX3CharacterKinematicDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libPhysX3CommonDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libPhysX3CookingDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libPhysX3ExtensionsDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libPhysX3VehicleDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libPhysXVisualDebuggerSDKDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libPxTaskDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libPvdRuntimeDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libSceneQueryDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx64/libSimulationControllerDEBUG.a)

            copy_file_to_binaries(/External/PhysX/lib/osx64/libPhysX3DEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libPhysXProfileSDKDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libLowLevelDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libLowLevelClothDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libPhysX3CharacterKinematicDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libPhysX3CommonDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libPhysX3CookingDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libPhysX3ExtensionsDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libPhysX3VehicleDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libPhysXVisualDebuggerSDKDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libPxTaskDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libPvdRuntimeDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libSceneQueryDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx64/libSimulationControllerDEBUG.a)

        elseif(${OPIFEX_OS_OSX32})
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libPhysX3DEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libPhysXProfileSDKDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libLowLevelDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libLowLevelClothDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libPhysX3CharacterKinematicDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libPhysX3CommonDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libPhysX3CookingDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libPhysX3ExtensionsDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libPhysX3VehicleDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libPhysXVisualDebuggerSDKDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libPxTaskDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libPvdRuntimeDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libSceneQueryDEBUG.a)
            target_link_libraries(${APPLICATION_TARGET} ${PROJECT_SOURCE_DIR}/External/PhysX/lib/osx32/libSimulationControllerDEBUG.a)

            copy_file_to_binaries(/External/PhysX/lib/osx32/libPhysX3DEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libPhysXProfileSDKDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libLowLevelDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libLowLevelClothDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libPhysX3CharacterKinematicDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libPhysX3CommonDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libPhysX3CookingDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libPhysX3ExtensionsDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libPhysX3VehicleDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libPhysXVisualDebuggerSDKDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libPxTaskDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libPvdRuntimeDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libSceneQueryDEBUG.a)
            copy_file_to_binaries(/External/PhysX/lib/osx32/libSimulationControllerDEBUG.a)
		endif()
	endif()

endmacro(add_opifex_physx)
