#pragma once

#include "./OPengine.h"

extern OPgameState GS_EXAMPLE_SELECTOR;

extern OPint       GS_EXAMPLE_AUDIO_AVAILABLE;
extern OPgameState GS_EXAMPLE_AUDIO;
extern OPint       GS_EXAMPLE_DEFERRED_AVAILABLE;
extern OPgameState GS_EXAMPLE_DEFERRED;
extern OPint       GS_EXAMPLE_MODEL_AVAILABLE;
extern OPgameState GS_EXAMPLE_MODEL;
extern OPint       GS_EXAMPLE_MYO_AVAILABLE;
extern OPgameState GS_EXAMPLE_MYO;
extern OPint       GS_EXAMPLE_OCULUS_AVAILABLE;
extern OPgameState GS_EXAMPLE_OCULUS;
extern OPint       GS_EXAMPLE_PARTICLESYSTEM_AVAILABLE;
extern OPgameState GS_EXAMPLE_PARTICLESYSTEM;
extern OPint       GS_EXAMPLE_PHYSICS_AVAILABLE;
extern OPgameState GS_EXAMPLE_PHYSICS;
extern OPint       GS_EXAMPLE_SKINNING_AVAILABLE;
extern OPgameState GS_EXAMPLE_SKINNING;
extern OPint       GS_EXAMPLE_SPINE_AVAILABLE;
extern OPgameState GS_EXAMPLE_SPINE;
extern OPint       GS_EXAMPLE_TEXTURED_AVAILABLE;
extern OPgameState GS_EXAMPLE_TEXTURED;
extern OPint       GS_EXAMPLE_SCRIPTING_AVAILABLE;
extern OPgameState GS_EXAMPLE_SCRIPTING;
extern OPint       GS_EXAMPLE_SPHERICALCUBE_AVAILABLE;
extern OPgameState GS_EXAMPLE_SPHERICALCUBE;
extern OPint       GS_EXAMPLE_SPRITE_AVAILABLE;
extern OPgameState GS_EXAMPLE_SPRITE;
extern OPint       GS_EXAMPLE_IMGUI_AVAILABLE;
extern OPgameState GS_EXAMPLE_IMGUI;