#ifndef OPENGINE_HUMAN_RENDERING_ATTRIBUTES
#define OPENGINE_HUMAN_RENDERING_ATTRIBUTES

enum OPattributes {
	OPATTR_POSITION = 0x01,
	OPATTR_UV = 0x02,
	OPATTR_TANGENT = 0x04,
	OPATTR_NORMAL = 0x08,
	OPATTR_COLOR = 0x10
};

#endif