#ifndef OPENGINE_HUMAN_INPUT_ENUMS_GAMEPADINDICES
#define OPENGINE_HUMAN_INPUT_ENUMS_GAMEPADINDICES

#ifdef OPIFEX_ANDROID

#endif

enum OPgamePadIndex
{
	OPGAMEPAD_ONE =  0,
	OPGAMEPAD_TWO =  1,
	OPGAMEPAD_THREE =2,
	OPGAMEPAD_FOUR = 3,
};

#endif