#ifndef OPENGINE_HUMAN_INPUT_ENUMS_GAMEPADAXES
#define OPENGINE_HUMAN_INPUT_ENUMS_GAMEPADAXES

#ifdef OPIFEX_ANDROID

enum OUYAGamePadAxes
{
    OUYA_AXIS_L2 = 17,
    OUYA_AXIS_LS_X = 0,
    OUYA_AXIS_LS_Y = 1,
    OUYA_AXIS_R2 = 18,
    OUYA_AXIS_RS_X = 11,
    OUYA_AXIS_RS_Y = 14,
};

#endif

enum OPgamePadAxis
{
	OPGAMEPADAXIS_LS_X				= 0,
	OPGAMEPADAXIS_LS_Y				= 1,
	OPGAMEPADAXIS_RS_X				= 2,
	OPGAMEPADAXIS_RS_Y				= 3,
	OPGAMEPADAXIS_L2				= 4,
	OPGAMEPADAXIS_R2				= 5,
	_OPGAMEPADAXIS_MAX				= 6
};

#endif