#ifndef OPENGINE_HUMAN_INPUT_ENUMS_GAMEPADBUTTONS
#define OPENGINE_HUMAN_INPUT_ENUMS_GAMEPADBUTTONS

#ifdef OPIFEX_ANDROID

typedef enum
{
    OUYA_BUTTON_A = 97,
    OUYA_BUTTON_DPAD_DOWN = 20,
    OUYA_BUTTON_DPAD_LEFT = 21,
    OUYA_BUTTON_DPAD_RIGHT = 22,
    OUYA_BUTTON_DPAD_UP = 19,
    OUYA_BUTTON_L1 = 102,
    OUYA_BUTTON_L2 = 104, // Use AXIS Values Instead
    OUYA_BUTTON_L3 = 106,
    OUYA_BUTTON_MENU = 82,
    OUYA_BUTTON_O = 96,
    OUYA_BUTTON_R1 = 103,
    OUYA_BUTTON_R2 = 105, // Use AXIS Values Instead
    OUYA_BUTTON_R3 = 107,
    OUYA_BUTTON_U = 99,
    OUYA_BUTTON_Y = 100
} OUYAGamePadButton;

#endif

enum OPgamePadButton
{
	OPGAMEPADBUTTON_DPAD_UP          = 0,
	OPGAMEPADBUTTON_DPAD_DOWN        = 1,
	OPGAMEPADBUTTON_DPAD_LEFT        = 2,
	OPGAMEPADBUTTON_DPAD_RIGHT       = 3,
	OPGAMEPADBUTTON_START            = 4,
	OPGAMEPADBUTTON_BACK             = 5,
	OPGAMEPADBUTTON_LEFT_THUMB       = 6,
	OPGAMEPADBUTTON_RIGHT_THUMB      = 7,
	OPGAMEPADBUTTON_LEFT_SHOULDER    = 8,
	OPGAMEPADBUTTON_RIGHT_SHOULDER   = 9,
	OPGAMEPADBUTTON_A                = 10,
	OPGAMEPADBUTTON_B                = 11,
	OPGAMEPADBUTTON_X                = 12,
	OPGAMEPADBUTTON_Y                = 13,
	_OPGAMEPADBUTTON_MAX			 = 14
};

#endif