#ifndef OPENGINE_HUMAN_INPUT_MOUSEKEY
#define OPENGINE_HUMAN_INPUT_MOUSEKEY

#include "./Core/include/OPtypes.h"

enum OPmouseKey {
	OPMOUSE_LBUTTON = 0,
	OPMOUSE_RBUTTON,
	OPMOUSE_CANCEL,
	OPMOUSE_MBUTTON,
	OPMOUSE_XBUTTON1,
	OPMOUSE_XBUTTON2,
	OPMOUSE_XBUTTON3,
	OPMOUSE_XBUTTON4,
	_OPMOUSE_MAX = 8
};

extern ui32 OPmouseMapping[_OPMOUSE_MAX];

#endif