
### Determine default OS to select for CMake variable OPIFEX_DEFAULT_OS


target_architecture( ARCHITECTURE )
SET(TARGET_ARCH_64 0)
if(${ARCHITECTURE} STREQUAL "x86_64")
	SET(TARGET_ARCH_64 1)
endif()

SET(OPIFEX_DEFAULT_OS "OPIFEX_LINUX32")

if(WIN32 AND TARGET_ARCH_64)
	SET(OPIFEX_DEFAULT_OS "OPIFEX_WIN64")
elseif(WIN32)
	SET(OPIFEX_DEFAULT_OS "OPIFEX_WIN32")
endif()

if(UNIX AND TARGET_ARCH_64)
	SET(OPIFEX_DEFAULT_OS "OPIFEX_LINUX64")
elseif(UNIX)
	SET(OPIFEX_DEFAULT_OS "OPIFEX_LINUX32")
endif()

if(APPLE AND TARGET_ARCH_64)
	SET(OPIFEX_DEFAULT_OS "OPIFEX_OSX64")
elseif(APPLE)
	SET(OPIFEX_DEFAULT_OS "OPIFEX_OSX32")
endif()
