#pragma once

struct OPnetworkOperation {
	enum Enum {
		OPNETWORK_OPERATION_ALLOW_DROPPED_PACKETS = 0,
		OPNETWORK_OPERATION_REQUEST_DROPPED_PACKETS = 1,
		OPNETWORK_OPERATION_SEQUENCED_PACKETS = 2,
	};
};