
### Helper Macros


if(${OPIFEX_OPTION_RELEASE})
	SET(BINARY_RELEASE_MODE "release")
else()
	SET(BINARY_RELEASE_MODE "debug")
endif()

include(${CMAKE_CURRENT_LIST_DIR}/macros/link_binary.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_opifex_executable.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_opifex_targets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_source_group.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_asset_group.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_asset_dir.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/copy_source_group.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/OPIFEX_EVAL.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/populate_binary_directory.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/set_binary_output.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/output_library.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/output_library_from.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/output_binary.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/copy_to_folder.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/copy_to_folder_msvc.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/copy_to_folder_msvc_vs.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/copy_from_binaries_on_build.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_opifex_includes.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_external_opifex_includes.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_opifex_assets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_opifex_defines.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_opifex_definitions.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/add_opifex_libraries.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/find_binary.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/find_dynamic.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/opifex_engine_status_messages.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/copy_file_to_binaries.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/macros/copy_to_binaries.cmake)
