option(OPIFEX_OPTION_OCULUS "Build the Oculus library into the engine" OFF)
option(OPIFEX_OPTION_MYO "Build the Myo library into the engine" OFF)
option(OPIFEX_OPTION_V8 "Build the V8 library into the engine" OFF)
option(OPIFEX_OPTION_NODEJS "Configure build files for Node.js module" OFF)
option(OPIFEX_OPTION_PHYSICS "Build the PhysX library into the engine" OFF)
option(OPIFEX_OPTION_SPINE "Build the Spine library into the engine" OFF)
option(OPIFEX_OPTION_FMOD "Build the FMod library into the engine" OFF)

option(OPIFEX_OPTION_RELEASE "Build the engine in release mode" OFF)
option(OPIFEX_OPTION_SHARED "Build the engine as shared libraries" OFF)