macro(add_asset_dir TARGET_LIST)
	# message(STATUS "!!! !!! ${TARGET_LIST} ${PROJECT_SOURCE_DIR}")
	add_asset_group(Assets/Audio "${PROJECT_SOURCE_DIR}/Assets/Audio" ${TARGET_LIST})
	add_asset_group(Assets/Fonts "${PROJECT_SOURCE_DIR}/Assets/Fonts" ${TARGET_LIST})
	add_asset_group(Assets/Models "${PROJECT_SOURCE_DIR}/Assets/Models" ${TARGET_LIST})
	add_asset_group(Assets/Shaders "${PROJECT_SOURCE_DIR}/Assets/Shaders" ${TARGET_LIST})
	add_asset_group(Assets/Shaders/OPENGL_2_0 "${PROJECT_SOURCE_DIR}/Assets/Shaders/OPENGL_2_0" ${TARGET_LIST})
	add_asset_group(Assets/Shaders/OPENGL_2_0/Common "${PROJECT_SOURCE_DIR}/Assets/Shaders/OPENGL_2_0/Common" ${TARGET_LIST})
	add_asset_group(Assets/Shaders/OPENGL_3_3 "${PROJECT_SOURCE_DIR}/Assets/Shaders/OPENGL_3_3" ${TARGET_LIST})
	add_asset_group(Assets/Shaders/OPENGL_3_3/Common "${PROJECT_SOURCE_DIR}/Assets/Shaders/OPENGL_3_3/Common" ${TARGET_LIST})
	add_asset_group(Assets/Shaders/OPENGL_ES_2_0 "${PROJECT_SOURCE_DIR}/Assets/Shaders/OPENGL_ES_2_0" ${TARGET_LIST})
	add_asset_group(Assets/Shaders/OPENGL_ES_2_0/Common "${PROJECT_SOURCE_DIR}/Assets/Shaders/OPENGL_ES_2_0/Common" ${TARGET_LIST})
	add_asset_group(Assets/Scripts "${PROJECT_SOURCE_DIR}/Assets/Scripts" ${TARGET_LIST})
	add_asset_group(Assets/Textures "${PROJECT_SOURCE_DIR}/Assets/Textures" ${TARGET_LIST})
endmacro(add_asset_dir)
