
macro(copy_source_group SOURCE_PATH DESTINATION_TARGET)

	message(STATUS "COPY FROM '${SOURCE_PATH}'' to '${DESTINATION_TARGET}'")
	file(GLOB TEMP_SRC "${SOURCE_PATH}/*")
	file(COPY ${TEMP_SRC} DESTINATION ${DESTINATION_TARGET}/)
	### INSTALL( DIRECTORY ${SOURCE_PATH} DESTINATION ${DESTINATION_TARGET} )

endmacro(copy_source_group)
