
macro(set_opifex_assets)

	# unset(OPIFEX_ASSETS)

	if(${OPIFEX_OPTION_RELEASE})
		SET(OPIFEX_ASSETS NULL)
	else()
		IF(NOT DEFINED OPIFEX_ASSETS_ADDITIONAL)
			SET(OPIFEX_ASSETS "${PROJECT_SOURCE_DIR}/Assets/")
		ELSE()
			SET(OPIFEX_ASSETS "${PROJECT_SOURCE_DIR}/Assets/${OPIFEX_ASSETS_ADDITIONAL}")
		ENDIF()
		# message(STATUS "OPIFEX ASSETS SET TO: ${OPIFEX_ASSETS}")
	endif()

endmacro(set_opifex_assets)
