#ifndef OPENGINE_HUMAN_RENDERING_ENUMS_TEXTURE_WRAP
#define OPENGINE_HUMAN_RENDERING_ENUMS_TEXTURE_WRAP

enum struct OPtextureWrap
{
	NONE = 0,
	REPEAT,
	CLAMP,
	MIRRORED_REPEAT,
	CLAMP_TO_EDGE,
	CLAMP_TO_BORDER
};

#endif