#ifndef OPENGINE_HUMAN_RENDERING_ENUMS_TEXTURE_FORMAT
#define OPENGINE_HUMAN_RENDERING_ENUMS_TEXTURE_FORMAT

enum struct OPtextureFormat
{
	NONE = 0,
	RGB,
	RGBA,
	LUMINANCE,
	LUMINANCE_ALPHA,
	DEPTH
};

#endif